// <auto-generated />
using System;
using AlfaBank.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlfaBank.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlfaBank.Core.Models.ApplicationStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CreditApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CreditApplicationId");

                    b.ToTable("ApplicationStatusHistory", (string)null);
                });

            modelBuilder.Entity("AlfaBank.Core.Models.ClientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EmploymentMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyExpenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RegistrationAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClientProfiles_UserId");

                    b.ToTable("ClientProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1990, 4, 15),
                            EmployerName = "ООО «Ромашка»",
                            EmploymentMonths = 84,
                            MonthlyExpenses = 45000m,
                            MonthlyIncome = 120000m,
                            PassportNumber = "45 12 345678",
                            RegistrationAddress = "г. Москва, ул. Тверская, д. 1, кв. 5",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1996, 11, 2),
                            EmployerName = "АО «Вектор»",
                            EmploymentMonths = 30,
                            MonthlyExpenses = 30000m,
                            MonthlyIncome = 85000m,
                            PassportNumber = "52 98 765432",
                            RegistrationAddress = "г. Санкт-Петербург, пр-т Невский, д. 20, кв. 44",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("AlfaBank.Core.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AnnualInterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date");

                    b.Property<int>("CreditApplicationId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditApplicationId")
                        .IsUnique()
                        .HasDatabaseName("IX_Credits_CreditApplicationId");

                    b.ToTable("Credits", (string)null);
                });

            modelBuilder.Entity("AlfaBank.Core.Models.CreditApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditProductId")
                        .HasColumnType("int");

                    b.Property<string>("DecisionComment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("PaymentSharePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("ScorePoints")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("CreditProductId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_CreditApplications_Status_CreatedAt");

                    b.ToTable("CreditApplications", (string)null);
                });

            modelBuilder.Entity("AlfaBank.Core.Models.CreditProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualInterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxTermMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinTermMonths")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CreditProducts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualInterestRate = 18.5m,
                            CreatedAt = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Кредит наличными на любые нужды без залога и поручителей.",
                            IsActive = true,
                            MaxAmount = 1500000m,
                            MaxTermMonths = 60,
                            MinAmount = 50000m,
                            MinTermMonths = 6,
                            Name = "Потребительский кредит"
                        },
                        new
                        {
                            Id = 2,
                            AnnualInterestRate = 16.0m,
                            CreatedAt = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Объединение нескольких кредитов в один по сниженной ставке.",
                            IsActive = true,
                            MaxAmount = 3000000m,
                            MaxTermMonths = 84,
                            MinAmount = 100000m,
                            MinTermMonths = 12,
                            Name = "Рефинансирование"
                        },
                        new
                        {
                            Id = 3,
                            AnnualInterestRate = 22.0m,
                            CreatedAt = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Оборотные средства для малого и среднего бизнеса.",
                            IsActive = true,
                            MaxAmount = 5000000m,
                            MaxTermMonths = 36,
                            MinAmount = 200000m,
                            MinTermMonths = 6,
                            Name = "Кредит для предпринимателей"
                        });
                });

            modelBuilder.Entity("AlfaBank.Core.Models.CreditScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("InterestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("date");

                    b.Property<decimal>("PaymentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingDebt")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditId", "Number")
                        .IsUnique()
                        .HasDatabaseName("IX_CreditScheduleItems_CreditId_Number");

                    b.ToTable("CreditScheduleItems", (string)null);
                });

            modelBuilder.Entity("AlfaBank.Core.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditId")
                        .HasColumnType("int");

                    b.Property<int>("CreditScheduleItemId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date");

                    b.Property<int>("RegisteredByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.HasIndex("CreditScheduleItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_CreditScheduleItemId");

                    b.HasIndex("RegisteredByUserId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("AlfaBank.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Login");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Соколова Ирина Петровна",
                            IsActive = true,
                            Login = "specialist",
                            PasswordHash = "PBKDF2-SHA256$210000$66LaxU3dH0LzWUowf+15zQ==$XSCjJo2HzBDOX93jvt79r/CgRtCYFVLss52ttpsnCKc=",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ковалёв Артём Игоревич",
                            IsActive = true,
                            Login = "administrator",
                            PasswordHash = "PBKDF2-SHA256$210000$LRfRnYHrBGfkj+TgEUqiwA==$z2PJtAbx9TX+7hoZu13WFVHqoVVkTEe1QkzZmwmniZk=",
                            Role = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Иванов Иван Иванович",
                            IsActive = true,
                            Login = "client",
                            PasswordHash = "PBKDF2-SHA256$210000$Y6SL/xSlIgIdQAWKWoIrMQ==$XL8oh5+Xzvp6DZaFa9UGzg0/2D/Z+tvM5vXyu3qdOp4=",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Петрова Анна Сергеевна",
                            IsActive = true,
                            Login = "client2",
                            PasswordHash = "PBKDF2-SHA256$210000$YYHFp2WHnQA7lebRkA7u7w==$LcqxYkyAVlWb7SHbiBUgTmJnQfYOF7VjfJS5+gXCA7M=",
                            Role = 1
                        });
                });

            modelBuilder.Entity("AlfaBank.Core.Models.ApplicationStatusHistory", b =>
                {
                    b.HasOne("AlfaBank.Core.Models.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlfaBank.Core.Models.CreditApplication", "CreditApplication")
                        .WithMany("StatusHistory")
                        .HasForeignKey("CreditApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("CreditApplication");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.ClientProfile", b =>
                {
                    b.HasOne("AlfaBank.Core.Models.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("AlfaBank.Core.Models.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.Credit", b =>
                {
                    b.HasOne("AlfaBank.Core.Models.CreditApplication", "CreditApplication")
                        .WithOne("Credit")
                        .HasForeignKey("AlfaBank.Core.Models.Credit", "CreditApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditApplication");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.CreditApplication", b =>
                {
                    b.HasOne("AlfaBank.Core.Models.ClientProfile", "ClientProfile")
                        .WithMany("Applications")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlfaBank.Core.Models.CreditProduct", "CreditProduct")
                        .WithMany("Applications")
                        .HasForeignKey("CreditProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlfaBank.Core.Models.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClientProfile");

                    b.Navigation("CreditProduct");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.CreditScheduleItem", b =>
                {
                    b.HasOne("AlfaBank.Core.Models.Credit", "Credit")
                        .WithMany("ScheduleItems")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credit");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.Payment", b =>
                {
                    b.HasOne("AlfaBank.Core.Models.Credit", "Credit")
                        .WithMany("Payments")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlfaBank.Core.Models.CreditScheduleItem", "CreditScheduleItem")
                        .WithOne("Payment")
                        .HasForeignKey("AlfaBank.Core.Models.Payment", "CreditScheduleItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlfaBank.Core.Models.User", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Credit");

                    b.Navigation("CreditScheduleItem");

                    b.Navigation("RegisteredBy");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.ClientProfile", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.Credit", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ScheduleItems");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.CreditApplication", b =>
                {
                    b.Navigation("Credit");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.CreditProduct", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.CreditScheduleItem", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("AlfaBank.Core.Models.User", b =>
                {
                    b.Navigation("ClientProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
